class Product:
    def __init__(self):
        self.Info = {
            'ps_category': '',
            'ps_product_name': '',
            'ps_product_description': '',
            'ps_sku_parent_short': '',
            'et_title_variation_integration_no': '',
            'et_title_variation_1': '',
            'et_title_option_for_variation_1': '',
            'et_title_image_per_variation': '',
            'et_title_variation_2': '',
            'et_title_option_for_variation_2': '',
            'ps_price': '',
            'ps_stock': '',
            'ps_sku_short': '',
            'ps_item_cover_image': '',
            'ps_item_image_1': '',
            'ps_item_image_2': '',
            'ps_item_image_3': '',
            'ps_item_image_4': '',
            'ps_item_image_5': '',
            'ps_item_image_6': '',
            'ps_item_image_7': '',
            'ps_item_image_8': '',
            'ps_weight': '',
            'ps_length': '',
            'ps_width': '',
            'ps_height': '',
            'channel_id_50018' : '',
            'channel_id_50022' : '',	
            'channel_id_50023' : '',	
            'channel_id_50024' : '',	
            'channel_id_50011' : '',	
            'channel_id_50010' : '',	
            'channel_id_50012' : '',	
            'channel_id_50016' : '',	
            'channel_id_50020' : '',	
            'channel_id_50015' : '',
            'ps_product_pre_order_dts': ''
        }

